# Generated by Django 4.1.7 on 2023-05-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_user_myfindings_user_myreports"),
    ]

    operations = [
        migrations.AddField(
            model_name="missingperson",
            name="contact",
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
