# Generated by Django 4.1.7 on 2023-04-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_user_name_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MissingPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=255)),
                ("identifying_info", models.CharField(max_length=100000)),
            ],
        ),
    ]
