# Generated by Django 4.1.7 on 2023-04-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_missingperson"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missingperson",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
