# Generated by Django 4.1.7 on 2023-05-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_missingpersonlocations_lattitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="missingpersonlocations",
            name="missingid",
            field=models.BigIntegerField(default="0"),
            preserve_default=False,
        ),
    ]
